basePath: /
definitions:
  main.MessageRequest:
    description: Request to send messages to recipients
    properties:
      message:
        description: |-
          @Description The message content to send
          @Example "Hello from Mowa API!"
        type: string
      to:
        description: |-
          @Description List of phone numbers or group names to send messages to
          @Example ["+1234567890", "family", "+0987654321"]
        items:
          type: string
        type: array
    required:
    - message
    - to
    type: object
  main.MessageResponse:
    description: Response containing results of message sending operations
    properties:
      results:
        description: '@Description List of results for each recipient'
        items:
          $ref: '#/definitions/main.MessageResult'
        type: array
    type: object
  main.MessageResult:
    description: Result of sending a message to a single recipient
    properties:
      error:
        description: '@Description Error message if the message failed to send'
        type: string
      recipient:
        description: |-
          @Description The recipient phone number or group name
          @Example "+1234567890"
        type: string
      success:
        description: '@Description Whether the message was sent successfully'
        type: boolean
    type: object
  main.StorageRequest:
    description: Request for file storage operations
    properties:
      content:
        description: |-
          @Description File content (required for POST operations)
          @Example "Hello, this is file content!"
        type: string
      path:
        description: |-
          @Description File path relative to storage directory
          @Example "/documents/example.txt"
        type: string
    type: object
  main.StorageResponse:
    description: Response from file storage operations
    properties:
      content:
        description: '@Description File content (for GET operations) or success message
          (for POST operations)'
        type: string
      error:
        description: '@Description Error message if the operation failed'
        type: string
      success:
        description: '@Description Whether the operation was successful'
        type: boolean
    type: object
  main.UptimeResponse:
    description: System uptime information
    properties:
      formatted:
        description: |-
          @Description Formatted uptime string (same as uptime)
          @Example "2 days, 3 hours, 45 minutes"
        type: string
      uptime:
        description: |-
          @Description Human-readable uptime string
          @Example "2 days, 3 hours, 45 minutes"
        type: string
      uptimeSeconds:
        description: |-
          @Description Uptime in seconds
          @Example 176700
        type: number
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: A simple API for sending messages and managing file storage
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Mowa API
  version: "1.0"
  x-logo:
    altText: Mowa Logo
    url: /assets/mowa-logo.png
paths:
  /api/messages:
    post:
      consumes:
      - application/json
      description: Send messages to one or more recipients via iMessage
      parameters:
      - description: Message request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/main.MessageRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Messages sent successfully
          schema:
            $ref: '#/definitions/main.MessageResponse'
        "400":
          description: Bad request - invalid input
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Send messages to recipients
      tags:
      - messages
  /api/storage:
    get:
      consumes:
      - application/json
      description: Handle both GET and POST requests for storage operations with JSON
        payload
      parameters:
      - description: Storage request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/main.StorageRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Storage operation completed successfully
          schema:
            $ref: '#/definitions/main.StorageResponse'
        "400":
          description: Bad request - invalid input
          schema:
            $ref: '#/definitions/main.StorageResponse'
        "404":
          description: File not found
          schema:
            $ref: '#/definitions/main.StorageResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/main.StorageResponse'
      summary: Handle storage operations
      tags:
      - storage
    post:
      consumes:
      - application/json
      description: Handle both GET and POST requests for storage operations with JSON
        payload
      parameters:
      - description: Storage request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/main.StorageRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Storage operation completed successfully
          schema:
            $ref: '#/definitions/main.StorageResponse'
        "400":
          description: Bad request - invalid input
          schema:
            $ref: '#/definitions/main.StorageResponse'
        "404":
          description: File not found
          schema:
            $ref: '#/definitions/main.StorageResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/main.StorageResponse'
      summary: Handle storage operations
      tags:
      - storage
  /api/storage/{path}:
    get:
      description: Handle GET requests for storage operations where path is provided
        in URL
      parameters:
      - default: /example.txt
        description: File path
        in: path
        name: path
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: File content
          schema:
            type: string
        "400":
          description: Bad request - invalid path
          schema:
            $ref: '#/definitions/main.StorageResponse'
        "404":
          description: File not found
          schema:
            $ref: '#/definitions/main.StorageResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/main.StorageResponse'
      summary: Handle storage operations with URL path
      tags:
      - storage
  /api/uptime:
    get:
      description: Get the current system uptime information
      produces:
      - application/json
      responses:
        "200":
          description: Uptime information retrieved successfully
          schema:
            $ref: '#/definitions/main.UptimeResponse'
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Get system uptime
      tags:
      - system
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
