name: Build on macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Download dependencies
      run: go mod download
      
    - name: Install swag
      run: go install github.com/swaggo/swag/cmd/swag@latest
      
    - name: Generate Swagger documentation
      run: swag init
      
    - name: Verify Swagger files
      run: |
        echo "Checking generated swagger files..."
        ls -la docs/
        test -f docs/swagger.json
        test -f docs/swagger.yaml
        test -f docs/docs.go
        echo "✅ Swagger files generated successfully"
      
    - name: Build project
      run: go build -o mowa
      
    - name: Test embedded swagger documentation
      run: |
        echo "Testing embedded swagger documentation..."
        timeout 10s ./mowa &
        sleep 3
        curl -f http://localhost:8080/swagger/doc.json > /dev/null && echo "✅ JSON endpoint works"
        curl -f http://localhost:8080/swagger/doc.yaml > /dev/null && echo "✅ YAML endpoint works"
        pkill -f mowa || true